--Translator Thiago Franco
--if GetLocale() ~= "enUS" then return end
local _, qcc = ...
qcc.L_Categories = {}
local L_Categories = qcc.L_Categories

L_Categories["Category_Cook"] = "Cooking"
L_Categories["Category_Arch"] = "Archaeology"
L_Categories["Category_FAid"] = "First Aid"
L_Categories["Category_Fish"] = "Fishing"
L_Categories["Category_PvP"] = "PvP"
L_Categories["Category_PvP_Tooltip"] = "Player versus Player"
L_Categories["Category_Professions"] = "Professions"
L_Categories["Category_Time"] = "Limited"
L_Categories["Category_Time_Tooltip"] = "Unavailable after the Siege of Orgrimmar."
L_Categories["Category_Race"] = "Racing"
L_Categories["Category_SET_1"] = "Set 1"
L_Categories["Category_SET_2"] = "Set 2"
L_Categories["Category_SET_3"] = "Set 3"
L_Categories["Category_Drop"] = "Looted"
L_Categories["Category_Drop_Tooltip"] = "This quest begin by looting an item from an object or corpse."
L_Categories["Category_Shop"] = "Shop"
L_Categories["Category_Shop_Tooltip"] = "This quest begin with an item sold by the quest giver."
L_Categories["Category_Auto"] = "Auto"
L_Categories["Category_Auto_Tooltip"] = "This quest begin imediatly after it's pre-requisite is completed."
L_Categories["Category_Krasarang_Sturdy_Crab_Crate"] = "Sturdy Crab Crate"
L_Categories["Category_Krasarang_Sturdy_Crane_Snare"] = "Sturdy Crane Snare"
L_Categories["Category_Krasarang_Sturdy_Tiger_Trap"] = "Sturdy Tiger Trap"
L_Categories["Category_Chi-Ji"] = "Cradle of Chi-Ji"
L_Categories["Category_Niuzao"] = "Niuzao Temple"
L_Categories["Category_Jade_Serpent"] = "Temple of the Jade Serpent"
L_Categories["Category_White_Tiger"] = "Temple of the White Tiger"