--Translator ZamestoTV
if GetLocale() ~= "ruRU" then return end
local _, qcc = ...
qcc.L_Categories = {}
local L_Categories = qcc.L_Categories

L_Categories["Category_Cook"] = "Кулинария"
L_Categories["Category_Arch"] = "Археология"
L_Categories["Category_FAid"] = "Первая помощь"
L_Categories["Category_Fish"] = "Рыбная ловля"
L_Categories["Category_PvP"] = "PvP"
L_Categories["Category_PvP_Tooltip"] = "Игрок против игрока"
L_Categories["Category_Professions"] = "Профессии"
L_Categories["Category_Time"] = "Ограниченные"
L_Categories["Category_Time_Tooltip"] = "Недоступно после осады Оргриммара."
L_Categories["Category_Race"] = "Гонки"
L_Categories["Category_SET_1"] = "Набор 1"
L_Categories["Category_SET_2"] = "Набор 2"
L_Categories["Category_SET_3"] = "Набор 3"
L_Categories["Category_Drop"] = "Looted"
L_Categories["Category_Drop_Tooltip"] = "This quest begin by looting an item from an object or corpse."
L_Categories["Category_Shop"] = "Shop"
L_Categories["Category_Shop_Tooltip"] = "This quest begin with an item sold by the quest giver."
L_Categories["Category_Auto"] = "Auto"
L_Categories["Category_Auto_Tooltip"] = "This quest begin imediatly after it's pre-requisite is completed."
L_Categories["Category_Krasarang_Sturdy_Crab_Crate"] = "Прочный ящик для крабов"
L_Categories["Category_Krasarang_Sturdy_Crane_Snare"] = "Прочный журавлиный силок"
L_Categories["Category_Krasarang_Sturdy_Tiger_Trap"] = "Прочная тигриная ловушка"
L_Categories["Category_Chi-Ji"] = "Колыбель Чи-Цзи"
L_Categories["Category_Niuzao"] = "Храм Нюцзао"
L_Categories["Category_Jade_Serpent"] = "Храм Нефритовой Змеи"
L_Categories["Category_White_Tiger"] = "Храм Белого Тигра"